task 0

diff --git a/python-hello_world/0-run b/python-hello_world/0-run
--- a/python-hello_world/0-run
+++ b/python-hello_world/0-run
@@ -2,26 +2,15 @@
 
 # Check if the environment variable PYFILE is set
 if [ -z "$PYFILE" ]; then
-    echo "Error: The environment variable PYFILE is not set."
-    exit 1
+	    echo "Error: The environment variable PYFILE is not set."
+	        exit 1
 fi
 
 # Check if the specified Python file exists
 if [ ! -f "$PYFILE" ]; then
-    echo "Error: The file $PYFILE does not exist."
-    exit 1
+	    echo "Error: The file $PYFILE does not exist."
+	        exit 1
 fi
 
 # Run the Python script
-python "$PYFILE"
-
-# Capture the exit status of the Python script
-STATUS=$?
-
-# Check if the Python script ran successfully
-if [ $STATUS -ne 0 ]; then
-    echo "Error: The Python script $PYFILE exited with status $STATUS."
-    exit $STATUS
-fi
-
-echo "Python script $PYFILE ran successfully."
+python3 "$PYFILE"
